### ISSUE TITLE
Migrate private repositories

### ISSUE THREAD

**Issue by nicopace** [valeriangalliat/gogs-migrate#2]
Why didn't it migrate private repos too?
Is there any way I can help for that?
Thanks,

**Comment by valeriangalliat** [comment]
Hey @nicopace,

Unfortunately private repositories are not (yet) supported, from the readme:

> Currently, only GitHub is supported, with the --github-user option. It will find only the public repositories, and there's currently no way to configure credentials to access private repositories.

It's a desirable feature though, just that I don't have any private repositories so I didn't have the need for this feature nor any way to test it.

I think the easiest way is to use a [personal access token](https://developer.github.com/v3/auth/#via-oauth-tokens) for the authentication. I made a branch for this in [`feature/github-token`](https://github.com/valeriangalliat/gogs-migrate/tree/feature/github-token), would you mind trying it to see if it's enough to migrate private repos?

<del>Also I need some way to make private repos also private on Gogs side no matter if `--private` is given or not... this branch is not yet production ready!</del> Just realized that [I thought of this case already](https://github.com/valeriangalliat/gogs-migrate/blob/9cf17b7c3dd5d784e69c0f280fef876167e60e19/src/index.js#L24)!

**Comment by nicopace** [comment]
Will test it, thanks!

**Comment by valeriangalliat** [comment]
I merged and published this as 2.1.0, I'm not yet sure it really allows to access private repos but in theory it should!
